- name: Run docker compose pull and up
  hosts: immitch
  tasks:
    - name: Pull latest Docker image
      community.docker.docker_compose_v2_pull:
       project_src: /immich-app 
    
    - name: Start the container
      ansible.builtin.shell: |
        docker compose up -d
      args:
        chdir: /immich-app

    - name: Prune dnagling images
      community.docker.docker_prune:
        images: true
        timeout: 300
      retries: 3
      delay: 10
