    name: Update Immich Server

    on:
      schedule:
        - cron: '0 23 * * *' # Run daily at 11:00 PM
      workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-latest # Or your desired runner

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Connect to Twingate
          uses: twingate/github-action@v1 # Use the latest version
          with:
            service-key: ${{ secrets.TWINGATE_SERVICE_KEY }} # Reference your secret

        - name: Run playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            # Required, playbook filepath
            playbook: upgrade_immitch_server.yml
            # Optional, directory where playbooks live
            directory: ./
            # Optional, literal inventory file contents
            inventory: ./inventory.ini
            # Optional, encrypted vault password
            vault_password: ${{secrets.ANSIBLE_VAULT_PASSWORD}}